// Mapa de nombres de equipo distintos (según la fuente: TheSportsDB,
// football-data.org, openfootball) que son en realidad el mismo equipo,
// hacia un nombre único para guardar y mostrar.
const teamAliases = {
  // España
  "elche cf": "Elche",
  "levante ud": "Levante",
  "rcd espanyol": "Espanyol",
  "rcd espanyol de barcelona": "Espanyol",
  "villarreal cf": "Villarreal",
  "athletic club": "Athletic Bilbao",
  "deportivo alavés": "Alaves",
  "getafe cf": "Getafe",
  "málaga cf": "Malaga",
  "rayo vallecano de madrid": "Rayo Vallecano",
  "real betis balompié": "Real Betis",
  "real sociedad de fútbol": "Real Sociedad",
  "sevilla fc": "Sevilla",
  "valencia cf": "Valencia",
  "real madrid cf": "Real Madrid",
  "club atlético de madrid": "Atletico Madrid",
  "real racing club de santander": "Racing Santander",
  "rc deportivo la coruña": "Deportivo La Coruna",
  "ca osasuna": "Osasuna",
  "rc celta de vigo": "Celta Vigo",
  "real valladolid cf": "Real Valladolid",

  // Alemania (Bundesliga)
  "bayern munchen": "FC Bayern München",
  "bayern münchen": "FC Bayern München",
  "fsv mainz 05": "1. FSV Mainz 05",
  "bayer leverkusen": "Bayer 04 Leverkusen",
  "union berlin": "1. FC Union Berlin",
  "1899 hoffenheim": "TSG 1899 Hoffenheim",
  "sv elversberg": "SV 07 Elversberg",

  // Brasil
  "atletico mineiro": "CA Mineiro",
  "atletico paranaense": "CA Paranaense",
  "bahia": "EC Bahia",
  "botafogo rj": "Botafogo FR",
  "bragantino": "RB Bragantino",
  "chapecoense sc": "Chapecoense AF",
  "corinthians paulista (sp)": "SC Corinthians Paulista",
  "coritiba pr": "Coritiba FBC",
  "cruzeiro": "Cruzeiro EC",
  "flamengo": "CR Flamengo",
  "fluminense rj": "Fluminense FC",
  "gremio (rs)": "Grêmio FBPA",
  "internacional rs": "SC Internacional",
  "mirassol": "Mirassol FC",
  "palmeiras": "SE Palmeiras",
  "remo belem (pa)": "Clube do Remo",
  "santos": "Santos FC",
  "sao paulo": "São Paulo FC",
  "vasco da gama": "CR Vasco da Gama",
  "vitoria ba": "EC Vitória",
  "atletico-mg": "CA Mineiro",
  "vitoria": "EC Vitória",

  // Inglaterra - Championship
"blackburn rovers fc": "Blackburn",
"bolton wanderers fc": "Bolton",
"bristol city fc": "Bristol City",
"cardiff city fc": "Cardiff",
"charlton athletic fc": "Charlton",
"derby county fc": "Derby",
"middlesbrough fc": "Middlesbrough",
"norwich city fc": "Norwich",
"southampton fc": "Southampton",
"watford fc": "Watford",
"wolverhampton wanderers fc": "Wolves",
"wrexham afc": "Wrexham",
"burnley fc": "Burnley",
"portsmouth fc": "Portsmouth",
"preston north end fc": "Preston",
"stoke city fc": "Stoke City",
"swansea city afc": "Swansea",
"west bromwich albion fc": "West Brom",
"west ham united fc": "West Ham",
"birmingham city fc": "Birmingham",
"lincoln city fc": "Lincoln",
"millwall fc": "Millwall",
"queens park rangers fc": "QPR",
"sheffield united fc": "Sheffield Utd",

// Francia - Ligue 1
"as monaco fc": "AS Monaco",
"aj auxerre": "Auxerre",
"le havre ac": "Le Havre",
"racing club de lens": "Lens",
"lille osc": "Lille",
"olympique lyonnais": "Lyon",
"olympique de marseille": "Olympique Marseille",
"stade rennais fc 1901": "Rennes",
"stade brestois 29": "Stade Brestois",
"rc strasbourg alsace": "Strasbourg",
"toulouse fc": "Toulouse",
"angers sco": "Angers",
"paris saint-germain fc": "Paris Saint-Germain",
"paris saint germain": "Paris Saint-Germain",
"estac troyes": "ES Troyes AC",

// Inglaterra - Premier League
"arsenal fc": "Arsenal",
"aston villa fc": "Aston Villa",
"brentford fc": "Brentford",
"brighton & hove albion fc": "Brighton & Hove Albion",
"chelsea fc": "Chelsea",
"crystal palace fc": "Crystal Palace",
"everton fc": "Everton",
"fulham fc": "Fulham",
"leeds united fc": "Leeds United",
"leicester city fc": "Leicester City",
"liverpool fc": "Liverpool",
"manchester city fc": "Manchester City",
"manchester united fc": "Manchester United",
"newcastle united fc": "Newcastle United",
"nottingham forest fc": "Nottingham Forest",
"southampton fc": "Southampton",
"sunderland afc": "Sunderland",
"tottenham hotspur fc": "Tottenham Hotspur",
"west ham united fc": "West Ham United",
"wolverhampton wanderers fc": "Wolverhampton Wanderers",
"bournemouth": "AFC Bournemouth",
"burnley fc": "Burnley",

// Italia - Serie A
"ac monza": "Monza",
"acf fiorentina": "Fiorentina",
"atalanta bc": "Atalanta",
"bologna fc 1909": "Bologna",
"cagliari calcio": "Cagliari",
"como 1907": "Como",
"empoli fc": "Empoli",
"fc internazionale milano": "Inter",
"frosinone calcio": "Frosinone",
"genoa cfc": "Genoa",
"hellas verona fc": "Hellas Verona",
"juventus fc": "Juventus",
"ss lazio": "Lazio",
"ac milan": "Milan",
"parma calcio 1913": "Parma",
"ssc napoli": "Napoli",
"torino fc": "Torino",
"udinese calcio": "Udinese",
"us lecce": "Lecce",
"us sassuolo calcio": "Sassuolo",
"venezia fc": "Venezia",

};

function normalize(name) {
  return String(name || "").toLowerCase().trim();
}

function getDisplayTeamName(rawName) {
  const key = normalize(rawName);
  return teamAliases[key] || rawName;
}

module.exports = { getDisplayTeamName };